version: '3'

services:
  #use ldap for auth
  ldap:
    build: ./Dockerfiles/ldap
    volumes:
      - ./data/openldap-data:/var/lib/openldap/openldap-data

  postfix:
    env_file: ./server.env
    build: ./Dockerfiles/postfix
    volumes:
      - ./Dockerfiles/common:/common
    ports:
      - 25:25
      - 587:587
    #depends_on:
    #  - ldap

  nginx:
    env_file: ./server.env
    build: ./Dockerfiles/nginx
    restart: unless-stopped
    volumes:
      - ./Dockerfiles/common:/common
    ports:
      - 80:80
      - 443:443
    #depends_on:
      #- rocketchat
    #restart: always
